export type RawPlayer = Record<string, string>;
export type NormalizedPlayer = Record<string, string | number | RawPlayer | undefined> & {
  id: string;
  raw: RawPlayer;
  name: string;
  age?: number;
  club?: string;
  nationality?: string;
  secondNationality?: string;
  based?: string;
  basedIn?: string;
  division?: string;
  uid?: string;
  position?: string;
  preferredFoot?: string;
  leftFoot?: string;
  rightFoot?: string;
  height?: string;
  valueM?: number;
  valueLowM?: number;
  valueHighM?: number;
  transferValueStatus?: "fixed" | "range" | "not_for_sale" | "missing";
  wageK?: number;
  minutes?: number;
  apps?: number;
  goals?: number;
  assists?: number;
  averageRating?: number;
};

export type WeightedMetric = { key: string; weight: number; label?: string; inverse?: boolean };
export type FloorPenalty = { attribute: string; lt: number; minus: number };
export type ScoreCap = { attribute?: string; lt?: number; all?: { attribute: string; lt: number }[]; positionNotAtLeast?: "Competent"; noCentralForwardSuitability?: boolean; maxRoleScore: number };
export type WarningThreshold = { attribute: string; lt: number; label: string };
export type RoleConfig = {
  id: RoleId;
  shortName: string;
  label: string;
  duty: string;
  ageCurveGroup: "goalkeeper" | "defenderMidfielder" | "attacker";
  positions: string[];
  footRule: "FB_AT_LB" | "FB_AT_RB" | "IF_SU_LW" | "IF_SU_RW" | "BPD_SIDE_AWARE" | "CENTRAL_NEUTRAL" | "CENTRAL_NEUTRAL_PLUS_TWO_FOOT";
  attributeWeights: Record<string, number>;
  positiveStatWeights: Record<string, number>;
  negativeStatPenalties: Record<string, number>;
  floorPenalties: FloorPenalty[];
  scoreCaps?: ScoreCap[];
  warnings: WarningThreshold[];
};
export type RoleId = "sk-su" | "fb-at" | "bpd-de" | "dm-su" | "if-su" | "am-at" | "af-at";
export type SlotId = "GK" | "LB" | "LCB" | "RCB" | "RB" | "LDM" | "RDM" | "LW" | "AMC" | "RW" | "ST";
export type ScorePart = { score?: number; available: number; expected: number };
export type RoleScore = {
  roleId: RoleId;
  slot?: SlotId;
  roleScore: number;
  recruitmentScore: number;
  confidenceScore: number;
  prospectScore: number;
  currentFormScore: number;
  attribute: ScorePart;
  stats: ScorePart;
  rawStats: number;
  hidden: ScorePart;
  position: ScorePart;
  value: ScorePart;
  wage: ScorePart;
  ageDevelopment: ScorePart;
  caps: string[];
  strengths: string[];
  weaknesses: string[];
  warnings: string[];
  explanation: string[];
};
export type ScoredPlayer = NormalizedPlayer & { scores: Record<RoleId, RoleScore> };
export type ValidationReport = {
  files: string[];
  playerCount: number;
  detectedColumns: string[];
  normalizedColumns: string[];
  missingRequired: string[];
  missingUseful: string[];
  messages: string[];
};
